import app from "../assets/images/app_icon_transparent.png";
import apple from "../assets/logins/apple.png";
import cart from "../assets/icons/icon-cart.png";
import check from "../assets/icons/icon-check.png";
import clock from "../assets/icons/icon-clock.png";
import del from "../assets/icons/icon-delete.png";
import exit from "../assets/icons/icon-exit.png";
import eye from "../assets/icons/icon-eye.png";
import eyeOff from "../assets/icons/icon-eye-off.png";
import google from "../assets/logins/google.png";
import gye from "../assets/icons/icon-gye.png";
import home from "../assets/icons/icon-home.png";
import info from "../assets/icons/icon-info.png";
import logo from "../assets/images/logo.png";
import menu from "../assets/icons/icon-menu.png";
import minus from "../assets/icons/icon-minus.png";
import moon from "../assets/icons/icon-moon.png";
import next from "../assets/icons/icon-next.png";
import plus from "../assets/icons/icon-plus.png";
import privacy from "../assets/icons/icon-privacy.png";
import profile from "../assets/icons/icon-profile.png";
import remove from "../assets/icons/icon-remove.png";
import star from "../assets/icons/icon-star.png";
import sun from "../assets/icons/icon-sun.png";
import terms from "../assets/icons/icon-terms.png";
import uio from "../assets/icons/icon-uio.png";
import user from "../assets/icons/icon-user.png";

export const appIcon = app;
export const appleIcon = apple;
export const cartIcon = cart;
export const checkIcon = check;
export const clockIcon = clock;
export const deleteIcon = del;
export const exitIcon = exit;
export const eyeIcon = eye;
export const eyeOffIcon = eyeOff;
export const googleIcon = google;
export const gyeIcon = gye;
export const homeIcon = home;
export const infoIcon = info;
export const logoIcon = logo;
export const menuIcon = menu;
export const minusIcon = minus;
export const moonIcon = moon;
export const nextIcon = next;
export const plusIcon = plus;
export const privacyIcon = privacy;
export const profileIcon = profile;
export const removeIcon = remove;
export const starIcon = star;
export const sunIcon = sun;
export const termsIcon = terms;
export const uioIcon = uio;
export const userIcon = user;
